version: "3"
services:
 terms-service:
    image: ctrmdev.azurecr.io/terms-service:latest
    deploy:
      replicas: 1
      resources:
        restart_policy:
          condition: on-failure
    container_name: terms-service
    ports:
      - "8098:8098"
