versions: "3"
services:
  master-service:
  image: ctrmdev.azurecr.io/ctrm-config:latest
  deploy:
    replicas: 1
    resources:
    restart_policy:
      condition: on-failure
  container_name: ctrm-master-service
  ports:
    - "8888:8888"
      