version: "3"
services:
 limit-service:
    image: ctrmdev.azurecr.io/limit-service:latest
    deploy:
      replicas: 1
      resources:
        restart_policy:
          condition: on-failure
    container_name: limit-service
    ports:
      - "8094:8094"
